version: "3.9"

services:

  app:
    container_name: app
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - redis

  db:
    image: postgres:15.2
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - local:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2-rc-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379

  pgadmin:
    image: dpage/pgadmin4:2023-03-01-1
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  local:
  pgadmin:
